In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('smart_infrastructure_risk_dataset.csv')
df.head()

,complaint_id,complaint_text,category,severity,location,complaint_frequency,road_age_years,rainfall_level,traffic_density,damage_size,previous_accidents,repair_delay_days,risk_score,risk_level
0,1,Pothole on Ondipudur highway not repaired for ...,pothole,high,"Ondipudur, Coimbatore",40,23,low,high,7.17,9,126,73.06,high_risk
1,2,Structural crack near Kovaipudur flyover needs...,crack,medium,"Kovaipudur, Coimbatore",30,14,low,low,5.36,8,55,48.87,medium_risk
2,3,Storm drain clogged at Thudiyalur junction cre...,drainage,medium,"Thudiyalur, Coimbatore",30,30,low,low,9.17,15,162,81.78,high_risk
3,4,Electric sparks from transformer near Perur ju...,electrical,high,"Perur, Coimbatore",41,20,low,medium,8.16,13,100,79.38,high_risk
4,5,Bridge railings broken near Thudiyalur posing ...,bridge_damage,low,"Thudiyalur, Coimbatore",11,19,low,high,1.99,0,17,16.40,low_risk

In [3]:
inputs = df.drop('risk_level', axis='columns')
target = df['risk_level']

In [4]:
from sklearn.preprocessing import LabelEncoder

le_cat      = LabelEncoder()
le_severity = LabelEncoder()
le_rainfall = LabelEncoder()
le_traffic  = LabelEncoder()

In [6]:
inputs['category_n']  = le_cat.fit_transform(inputs['category'])
inputs['severity_n']  = le_severity.fit_transform(inputs['severity'])
inputs['rainfall_n']  = le_rainfall.fit_transform(inputs['rainfall_level'])
inputs['traffic_n']   = le_traffic.fit_transform(inputs['traffic_density'])

In [7]:
inputs

,complaint_id,complaint_text,category,severity,location,complaint_frequency,road_age_years,rainfall_level,traffic_density,damage_size,previous_accidents,repair_delay_days,risk_score,category_n,severity_n,rainfall_n,traffic_n
0,1,Pothole on Ondipudur highway not repaired for ...,pothole,high,"Ondipudur, Coimbatore",40,23,low,high,7.17,9,126,73.06,4,0,1,0
1,2,Structural crack near Kovaipudur flyover needs...,crack,medium,"Kovaipudur, Coimbatore",30,14,low,low,5.36,8,55,48.87,1,2,1,1
2,3,Storm drain clogged at Thudiyalur junction cre...,drainage,medium,"Thudiyalur, Coimbatore",30,30,low,low,9.17,15,162,81.78,2,2,1,1
3,4,Electric sparks from transformer near Perur ju...,electrical,high,"Perur, Coimbatore",41,20,low,medium,8.16,13,100,79.38,3,0,1,2
4,5,Bridge railings broken near Thudiyalur posing ...,bridge_damage,low,"Thudiyalur, Coimbatore",11,19,low,high,1.99,0,17,16.40,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Dangerous pothole near Ganapathy hospital entr...,pothole,low,"Ganapathy, Coimbatore",8,27,medium,high,1.26,3,0,14.62,4,1,2,0
996,997,Cracks on Mettupalayam Road road foundation ca...,crack,high,"Mettupalayam Road, Coimbatore",33,14,high,medium,8.74,6,108,68.47,1,0,0,2
997,998,Blocked drainage near Sowripalayam causing wat...,drainage,low,"Sowripalayam, Coimbatore",12,7,high,low,2.59,3,23,22.35,2,1,0,1
998,999,Fallen electric pole on Vellalore road blockin...,electrical,medium,"Vellalore, Coimbatore",15,6,low,medium,2.38,3,33,29.27,3,2,1,2
999,1000,Load bearing capacity of Kavundampalayam bridg...,bridge_damage,medium,"Kavundampalayam, Coimbatore",18,17,high,high,4.24,2,104,38.61,0,2,0,0

In [8]:
inputs_n = inputs.drop(
    ['complaint_id', 'complaint_text', 'location',
     'category', 'severity', 'rainfall_level', 'traffic_density'],
    axis='columns'
)

In [9]:
inputs_n

,complaint_frequency,road_age_years,damage_size,previous_accidents,repair_delay_days,risk_score,category_n,severity_n,rainfall_n,traffic_n
0,40,23,7.17,9,126,73.06,4,0,1,0
1,30,14,5.36,8,55,48.87,1,2,1,1
2,30,30,9.17,15,162,81.78,2,2,1,1
3,41,20,8.16,13,100,79.38,3,0,1,2
4,11,19,1.99,0,17,16.40,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...
995,8,27,1.26,3,0,14.62,4,1,2,0
996,33,14,8.74,6,108,68.47,1,0,0,2
997,12,7,2.59,3,23,22.35,2,1,0,1
998,15,6,2.38,3,33,29.27,3,2,1,2
999,18,17,4.24,2,104,38.61,0,2,0,0

In [10]:
target

0        high_risk
1      medium_risk
2        high_risk
3        high_risk
4         low_risk
          ...
995       low_risk
996      high_risk
997       low_risk
998       low_risk
999    medium_risk
Name: risk_level, Length: 1000, dtype: object

In [11]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [12]:
model.fit(inputs_n, target)

DecisionTreeClassifier()

In [13]:
model.score(inputs_n, target)

1.0

In [14]:
model.predict([[40, 23, 7.17, 9, 126, 73.06, 4, 0, 1, 0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['high_risk'], dtype=object)