In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('smart_infrastructure_risk_dataset.csv')
df.head()

,complaint_id,complaint_text,category,severity,location,complaint_frequency,road_age_years,rainfall_level,traffic_density,damage_size,previous_accidents,repair_delay_days,risk_score,risk_level
0,1,Pothole on Ondipudur highway not repaired for ...,pothole,high,"Ondipudur, Coimbatore",40,23,low,high,7.17,9,126,73.06,high_risk
1,2,Structural crack near Kovaipudur flyover needs...,crack,medium,"Kovaipudur, Coimbatore",30,14,low,low,5.36,8,55,48.87,medium_risk
2,3,Storm drain clogged at Thudiyalur junction cre...,drainage,medium,"Thudiyalur, Coimbatore",30,30,low,low,9.17,15,162,81.78,high_risk
3,4,Electric sparks from transformer near Perur ju...,electrical,high,"Perur, Coimbatore",41,20,low,medium,8.16,13,100,79.38,high_risk
4,5,Bridge railings broken near Thudiyalur posing ...,bridge_damage,low,"Thudiyalur, Coimbatore",11,19,low,high,1.99,0,17,16.40,low_risk

In [4]:
df.shape

(1000, 14)

In [6]:
df.dtypes

complaint_id             int64
complaint_text          object
category                object
severity                object
location                object
complaint_frequency      int64
road_age_years           int64
rainfall_level          object
traffic_density         object
damage_size            float64
previous_accidents       int64
repair_delay_days        int64
risk_score             float64
risk_level              object
dtype: object

In [7]:
print(df['risk_level'].value_counts())

risk_level
medium_risk    334
high_risk      333
low_risk       333
Name: count, dtype: int64

In [10]:
le_severity = LabelEncoder()
le_rainfall  = LabelEncoder()
le_traffic   = LabelEncoder()

df['severity_enc']  = le_severity.fit_transform(df['severity'])
df['rainfall_enc']  = le_rainfall.fit_transform(df['rainfall_level'])
df['traffic_enc']   = le_traffic.fit_transform(df['traffic_density'])


feature_cols = [
    'complaint_frequency', 'road_age_years', 'rainfall_enc',
    'traffic_enc', 'damage_size', 'previous_accidents',
    'repair_delay_days', 'severity_enc'
]

X = df[feature_cols].values
X

array([[ 40.,  23.,   1., ...,   9., 126.,   0.],
       [ 30.,  14.,   1., ...,   8.,  55.,   2.],
       [ 30.,  30.,   1., ...,  15., 162.,   2.],
       ...,
       [ 12.,   7.,   0., ...,   3.,  23.,   1.],
       [ 15.,   6.,   1., ...,   3.,  33.,   2.],
       [ 18.,  17.,   0., ...,   2., 104.,   2.]])

In [16]:
le_target = LabelEncoder()
y = le_target.fit_transform(df['risk_level'])
print('Classes:', le_target.classes_)
print('Encoded values sample:', y[:10])

Classes: ['high_risk' 'low_risk' 'medium_risk']
Encoded values sample: [0 2 0 0 1 2 1 0 2 2]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [13]:
model = LogisticRegression(max_iter=1000)

In [17]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [18]:
y_pred = model.predict(X_test)

In [19]:
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

Accuracy: 0.99

In [20]:
sample = [[40, 23, 1, 2, 7.17, 9, 126, 1]]
prediction = model.predict(sample)
print('Predicted Risk Level:', le_target.inverse_transform(prediction)[0])

Predicted Risk Level: high_risk